version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m5f3ei0a8koe"
s3_prefix = "sam-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
